package org.kyberpipe.client.utils

import android.util.Log
import java.util.concurrent.atomic.AtomicBoolean

/**
 * Lifecycle-agnostic owner of the cold-start ratchet snapshot restore
 * (AUDIT FINDING F1 — HIGH).
 *
 * The legacy design coupled the restore to `MainActivity.onCreate`: after a
 * process death / reboot, a service-only restart (BOOT_COMPLETED alarm,
 * START_STICKY) started the poll engine against an EMPTY Rust registry — the
 * AEAD-wrapped snapshot was never imported, every poll threw "No ratchet
 * session" (swallowed), and the background sync feature was silently dead
 * until the user opened the app.
 *
 * This object is invoked from BOTH MainActivity and PipeService /
 * KyberPipePollEngine. A process-wide [restoreDone] gate guarantees the import
 * runs exactly once per process no matter which path fires first:
 *
 *  - `KyberPipePollEngine.start()` restores on the IO dispatcher BEFORE the
 *    first poll, so a reboot never runs an empty-registry loop; and
 *  - `MainActivity.onCreate` still attempts it (app opened after a restart
 *    before the service restored) and is a no-op when the service already
 *    imported the snapshot.
 *
 * The live-registry check (`ratchetPeerIds().isNotEmpty()`) is retained as a
 * second line of defense for the warm-start / re-pair path: after a RE-PAIR
 * the fresh session lives in Rust while the persisted snapshot is from the
 * OLD pairing, and importing it would silently roll the session back (audit
 * finding #2).
 */
object RatchetSessionRestorer {

    private const val TAG = "KyberpipeRestore"

    private val restoreLock = Any()
    private val restoreDone = AtomicBoolean(false)

    /**
     * Run the single-flight cold-start restore. Safe to call concurrently from
     * any thread (the caller decides the dispatcher — IO in both production
     * call sites); only the first caller in the process executes the import.
     * Returns immediately when a restore has already been attempted or a live
     * session is present (warm start / re-pair).
     */
    fun restoreIfNeeded(settings: SettingsManager) {
        if (restoreDone.get()) return
        synchronized(restoreLock) {
            if (restoreDone.get()) return
            restoreDone.set(true)
            // Single-flight gate (audit finding #2): never restore over a live
            // session. On a process cold start the Rust registry is empty
            // (nothing survives a kill), so an empty registry is the exact
            // signal that distinguishes "cold start, restore the snapshot"
            // from "warm recreation / re-pair, keep the live session". The
            // AtomicBoolean above is the process-wide primary gate so two
            // concurrent callers (MainActivity + service) cannot both observe
            // an empty registry and both import.
            val livePeers = try {
                uniffi.core_crypto.ratchetPeerIds()
            } catch (e: Exception) {
                emptyList()
            }
            if (livePeers.isNotEmpty()) {
                Log.i(
                    TAG,
                    "Ratchet restore skipped: ${livePeers.size} live session(s) in Rust registry (warm start / re-pair) — audit finding #2"
                )
                return
            }
            // AUDIT F11 FIX: this is a confirmed COLD START (empty Rust
            // registry). Rust-side handles (keypair, KEM shared secret, session
            // key) are PROCESS-SCOPED, so the persisted u64 values from the
            // previous process are stale and must never be acted on — e.g. by
            // `destroyPairingHandles` on unpair (a no-op against a vanished
            // handle) or by any future feature that assumes a live handle.
            // Zero them; a fresh keypair handle is generated by
            // PairingState.loadKeyPair() when pairing (re)starts.
            settings.sessionKeyHandle = 0L
            settings.keypairHandle = 0L
            settings.kemHandleId = 0L
            restoreBlocking(settings)
        }
    }

    private fun restoreBlocking(settings: SettingsManager) {
        val peer = settings.peerRatchetIdentity
        if (peer.isEmpty()) return
        val snapshot = settings.ratchetSnapshot
        if (snapshot.isEmpty()) return
        try {
            // Audit finding #13: the snapshot is wrapped at rest with an
            // INDEPENDENT Keystore-backed key (not the session key). Stored
            // format: Base64("{nonce_hex}:{ciphertext_hex}").
            val wrapKeyHex = settings.ratchetSnapshotKey
            if (wrapKeyHex.isEmpty()) return
            val stored =
                android.util.Base64.decode(snapshot, android.util.Base64.NO_WRAP)
                    .toString(Charsets.UTF_8)
            val sep = stored.indexOf(':')
            if (sep > 0) {
                val nonce = stored.substring(0, sep).hexToByteArraySafe()
                val ct = stored.substring(sep + 1).hexToByteArraySafe()
                val wrapKey = wrapKeyHex.hexToByteArraySafe()
                if (nonce != null && ct != null && wrapKey != null) {
                    // AUDIT F10: the UniFFI binding for decryptWithRawKey32 is
                    // non-null today (a decryption failure surfaces as a thrown
                    // KyberException caught by the outer try), but the wipe must
                    // never run on a null result and never NPE inside a finally
                    // masking the real failure. `wipeAndImport` takes a nullable
                    // bytes parameter so the null path is genuine (and stays
                    // compilable if the binding ever maps the Rust Result to a
                    // nullable Option).
                    wipeAndImport(settings, peer, uniffi.core_crypto.decryptWithRawKey32(
                        wrapKey, nonce, ct
                    ))
                    wrapKey.fill(0)
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Ratchet restore failed: ${e.message}")
        }
    }

    /**
     * Wipe-and-import the decrypted snapshot, null-tolerant (AUDIT F10). The
     * parameter is nullable so the guard is genuine regardless of what the
     * UniFFI binding declares: on the non-null path the snapshot is imported
     * and then wiped in a finally; on the null path the exact failure is
     * logged. The legacy code wiped `bytes` in a finally without a null guard,
     * so a null (or a wipe throwing) masked the real restore failure.
     */
    private fun wipeAndImport(
        settings: SettingsManager,
        peer: String,
        bytes: ByteArray?,
    ) {
        if (bytes != null) {
            try {
                restoreSnapshotFromBytes(settings, bytes, peer)
            } finally {
                // AUDIT #14: `bytes` is the decrypted snapshot — full session
                // key material — wiped the moment the import (or its rollback
                // refusal) completes.
                bytes.fill(0)
            }
        } else {
            Log.w(
                TAG,
                "Ratchet restore failed: snapshot decryption returned null (KEK mismatch or corrupted blob)"
            )
        }
    }

    /**
     * Import a decrypted snapshot (rollback-checked, audit #2/#1) into the Rust
     * registry. Split from the decode path so the caller can zeroize the
     * decrypted bytes after the import (audit #14).
     */
    private fun restoreSnapshotFromBytes(settings: SettingsManager, bytes: ByteArray, peer: String) {
        // AUDIT #2 (follow-up): enforce the same monotonic rollback bound the
        // desktop store enforces. A snapshot whose watermark is STRICTLY below
        // the recorded high-water mark (an older blob restored from a device
        // backup, or same-user tampering) is refused — otherwise the send chain
        // rolls back and derived message keys + nonces are reused for new
        // plaintext. Equal = the current snapshot, accepted.
        val snapWm = try {
            uniffi.core_crypto.ratchetSnapshotWatermark(bytes)
        } catch (e: Exception) {
            null
        }
        if (snapWm != null && RatchetWatermarkStore.refuseRollback(
                snapWm,
                RatchetWatermarkStore.read(settings, peer)
            )
        ) {
            Log.w(
                TAG,
                "Ratchet restore refused: snapshot watermark is below the recorded high-water mark (rollback) — audit finding #2"
            )
        } else {
            uniffi.core_crypto.ratchetImportSession(peer, bytes)
            // Record the imported watermark (max with stored) so the monotonic
            // bound survives restarts.
            snapWm?.let { wm ->
                RatchetWatermarkStore.update(settings, peer, wm)
            }
        }
    }
}

/** Hex string → byte array, or null on malformed input (audit finding #13). */
private fun String.hexToByteArraySafe(): ByteArray? {
    if (length % 2 != 0) return null
    return try {
        ByteArray(length / 2) { i ->
            ((Character.digit(this[i * 2], 16) shl 4) + Character.digit(this[i * 2 + 1], 16)).toByte()
        }
    } catch (e: Exception) {
        null
    }
}
